apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: financial-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: financial-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 20
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 10
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 15
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 5
      - type: Pods
        value: 4
        periodSeconds: 5
      selectPolicy: Max