env:
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-master-credentials
        key: password

config:
  outputs: |
    [OUTPUT]
        Name es
        Match *
        Host elasticsearch-master
        Port 9200
        HTTP_User elastic
        HTTP_Passwd ${ELASTIC_PASSWORD}
        tls On
        tls.verify Off
        Logstash_Format On
        Replace_Dots On
        Suppress_Type_Name On  
