apiVersion: v1
kind: Service
metadata:
    labels:
        app: iris-classifier
    name: iris-classifier
spec:
    ports:
    - name: predict
      targetPort: iris-port
      port: 5000
      nodePort: 30500
    selector:
      app: iris-classifier
    type: NodePort
