apiVersion: yaks.citrusframework.org/v1alpha1
kind: Test
metadata:
  name: nginx-example
spec:
  source:
    name: example.feature
    content: |-
      Feature: Verify NGINX is running

        Scenario: Run NGINX
          Given Kubernetes namespace experiment
          Given load Kubernetes resource nginx.yaml

        Background:
          Given URL: http://my-nginx.experiment

        Scenario: Get a result from API
          When send GET /
          Then receive HTTP 200 OK