apiVersion: v1
kind: Pod
metadata:
  name: tools-one
  labels:
    name: tools
spec:
  containers:
  - name: tools
    image: mbentley/bind-tools@sha256:9ae36015931b9db2b4574e1a5f34b6305f59b83e04aa8469791622d874abac71
    command: ["/bin/sh", "-ec", "sleep 60000"]
---
apiVersion: v1
kind: Pod
metadata:
  name: tools-two
  labels:
    name: tools
spec:
  containers:
  - name: tools
    image: mbentley/bind-tools@sha256:9ae36015931b9db2b4574e1a5f34b6305f59b83e04aa8469791622d874abac71
    command: ["/bin/sh", "-ec", "sleep 60000"]
