# Customize of rabbitmq-ha chart found here: 
# https://artifacthub.io/packages/helm/bitnami/rabbitmq

# Requested Rabbit MQ "nodes" (StatefulSet Pods), not to be confused with Kubernetes "nodes".
replicaCount: 2

# Exposed dashboard as NodePort for demonstration purposes.
service:
  type: NodePort 
  managerNodePort: 31000

# Admin credentials, use these for sign in to RabbitMQ dashboard
auth:
  username: guest
  password: guest

persistence:
  enabled: false
