apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-lister
  namespace: namespace-dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-lister
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-lister-binding
subjects:
  - kind: ServiceAccount
    name: namespace-lister
    namespace: namespace-dashboard
roleRef:
  kind: ClusterRole
  name: namespace-lister
  apiGroup: rbac.authorization.k8s.io
