# Customize of the chart found here: 
# https://artifacthub.io/packages/helm/bitnami/redis

# Requested Redis "nodes" (StatefulSet Pods), not to be confused with Kubernetes "nodes".
replica:
  replicaCount: 2
  persistence:
    enabled: false

# Exposed dashboard as NodePort for demonstration purposes.
master:
  service:
    type: NodePort
    nodePorts:
      redis: "30379"
  persistence:
    enabled: false

# No credentials or persistence for this demonstration
auth:
  enabled: false
