KafkaClient {
       org.apache.kafka.common.security.plain.PlainLoginModule required
       username="user"
       password="StrimziLetMeIn";
};

Client {
       org.apache.zookeeper.server.auth.DigestLoginModule required
       username="user"
       password="StrimziLetMeIn";
};
