apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kuard-deployment
  labels:
    app: kuard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:blue
        name: kuard
        resources:
          requests:
            cpu: "1000m"
            memory: "256Mi"
          limits:
            cpu: "1000m"
            memory: "256Mi"
